<!DOCTYPE html>
<head>
<html lang="en" class="csstransforms csstransforms3d csstransitions" hola_ext_inject="disabled"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Colegio de Medicina Critica de Jalisco A.C</title>
<meta name="keywords" content="Colegio de Medicina Critica de Jalisco A.C, Medicina Crítica, Terapia intensiva, Intensivistas,congresos, sesiones academicas, congreson nacional, medicina, critica">
<meta name="description" content="Somos una asociación civil con sentido social que agrupa a los Médicos Intensivistas de Jalisco, con el propósito de alcanzar la excelencia en la atención integral de los pacientes críticos.">
<!-- FONTS ONLINE -->
<link href='http://fonts.googleapis.com/css?family=Raleway:500,600,700,100,800,900,400,200,300' rel='stylesheet' type='text/css'>

{{-- {{ Html::style(asset('assets/css/css')) }} --}}
{{ Html::style(asset('assets/css/bootstrap.min.css')) }}
{{ Html::style(asset('assets/css/main.css')) }}
{{ Html::style(asset('assets/css/style.css')) }}
{{ Html::style(asset('assets/css/responsive.css')) }}
{{ Html::style(asset('assets/css/animate.css')) }}
{{ Html::style(asset('assets/css/font-awesome.min.css')) }}
{{ Html::style(asset('assets/css/ionicons.min.css')) }}
{{ Html::style(asset('assets/css/custom.css')) }}
<style type="text/css"></style></head>
<body>
    <!-- #region Jssor Slider Begin -->
    <!-- Generated by Jssor Slider Maker. -->
    <!-- This demo works with jquery library -->

    {{ Html::script(asset('assets/js/jquery-1.11.3.min.js')) }}
<script src="http://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.2" async></script>
<div id="wrap">
    <!-- TOP BAR ===========================================-->
    <div class="top-bar light">
        <div class="container">
            <ul class="pull-left">
                <li><span><a href="{{ url('admin') }}" target="_blank" style="color: #0024ff">LOGIN</a></li></span>
                <li>|</li>
                <li><span><a href="#" onclick="alert('Proximamente!')" style="color: #ff0000">AFILIATE!</a></span></li>
            </ul>

            <!-- SOCIAL ICONS ===========================================-->
            <ul class="social_icons">
                <li class="facebook"><a href="https://www.facebook.com/Colegio-de-Medicina-Critica-de-Jalisco-AC-114043575295415/." target="_blank"><i class="fa fa-facebook"></i> </a></li>
                <li class="twitter"><a href="https://twitter.com/MedCrit_Jal" target="_blank"><i class="fa fa-twitter"></i> </a></li>
                <li class="youtube"><a href="https://www.youtube.com/channel/UC45hO7nGvG6x0uQBqcuEWEQ" target="_blank"><i class="fa fa-youtube"></i> </a></li>
            </ul>
        </div>
    </div>

  <header>
    <div class="container">
      <div class="logo"> <a href="{{ url('/') }}"><img src="{{ asset('assets/images/logo1.png')}}" alt=""></a> </div>
      <nav>
        <ul id="ownmenu" class="ownmenu">
          <li style=""><a href="{{ url('_cmcjal') }}">CMCJAL<span class="indicator"><i class="fa fa-angle-down"></i></span></a>
              <!--<ul class="dropdown">
                  <li><a href="{{ url('internacionales') }}">Expresidentes</a></li>
              </ul>-->
          </li>
          <li style=""><a href="{{ url('colegiados') }}">Colegiados<span class="indicator"><i class="fa fa-angle-down"></i></span></a>
              <ul class="dropdown">
                  <li><a href="{{ url('registro') }}" class="disabled">Afíliate</a></li>
                  </ul>
</li>
          <li style=""><a href="">Sesiones y Congresos<span class="indicator"><i class="fa fa-angle-down"></i></span></a>
            <ul class="dropdown">
              <li><a href="{{ url('internacionales') }}">Internacionales</a></li>
              <li><a href="{{ url('nacionales') }}">Nacionales</a></li>
                <li><a href="{{ url('locales') }}">Locales</a></li>
                <li><a href="{{ url('mensuales') }}">Sesiones Mensuales</a></li>
                <li><a href="{{ url('noticias') }}">Noticias</a></li>
            </ul>
          </li>
          {{-- <li style=""><a href="">Pacientes y familiares</a> </li> --}}
          <li style=""><a href="{{ url('galeria') }}">Galeria<span class="indicator"><i class="fa fa-angle-down"></i></span></a>
          <li style=""><a href="{{ url('contacto') }}">Contacto</a> </li>

          </li>
        </ul>
      </nav>
    </div>
  </header>
  @yield('content')



  <!--======= FOOTER =========-->
  <footer>
    <div class="container">

      <!-- Row -->
      <div class="row">

        <div class="col-md-3">
          <div class="latest-tweet">
          </div>
        </div>

        <!-- About Us -->
        <div class="col-md-6">
          <div class="small-info"> <img src="{{ asset('assets/images/logo-white.png')}}" alt="">
            <p>Somos una asociación civil con sentido social que agrupa a los Médicos Intensivistas de Jalisco, con el propósito de alcanzar la excelencia en la atención integral de los pacientes críticos.</p>
            <ul class="social_icons">
              <li class="facebook"><a target="_blank" href="https://www.facebook.com/Colegio-de-Medicina-Critica-de-Jalisco-AC-114043575295415/"><i class="fa fa-facebook"></i> </a></li>
              <li class="twitter"><a target="_blank" href="https://twitter.com/MedCrit_Jal"><i class="fa fa-twitter"></i> </a></li>
              <li class="youtube"><a target="_blank" href="https://www.youtube.com/channel/UC45hO7nGvG6x0uQBqcuEWEQ"><i class="fa fa-youtube"></i> </a></li>
            </ul>
          </div>
        </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Rights -->
    <div class="rights">
      <p>© {{ date('Y') }} CMCJAL </p>

    </div>
  </footer>
</div>
<!-- Wrap End -->

@yield('scripts')
{{ Html::script(asset('assets/js/jquery-1.11.0.min.js')) }}
{{ Html::script(asset('assets/js/bootstrap.min.js')) }}
{{ Html::script(asset('assets/js/own-menu.js')) }}
{{ Html::script(asset('assets/js/owl.carousel.min.js')) }}
{{ Html::script(asset('assets/js/jquery.superslides.js')) }}
{{ Html::script(asset('assets/js/masonry.pkgd.min.js')) }}
{{ Html::script(asset('assets/js/jquery.stellar.min.js')) }}
{{ Html::script(asset('assets/js/jquery-ui-1.10.3.custom.js')) }}
{{ Html::script(asset('assets/js/jquery.magnific-popup.min.js')) }}
{{ Html::script(asset('assets/js/jquery.isotope.min.js')) }}
{{ Html::script(asset('assets/js/jquery.flexslider-min.js')) }}
{{ Html::script(asset('assets/js/appointment.js')) }}
{{ Html::script(asset('assets/js/jquery.downCount.js')) }}
{{ Html::script(asset('assets/js/counter.js')) }}
{{ Html::script(asset('assets/js/main.js')) }}
{{ Html::script(asset('assets/js/jquery.scrollUp.min.js')) }}

<div id="ui-datepicker-div" class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all"></div></body></html>
